sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: '050516'
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tQEAuo9yY4iige3XdE5
    access-key-secret: 9VeWpOpA6y5OzwuoT1EXibr4GNxvz0
    bucket-name: java-ai-study-itheima
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
